!Copyright (c) 2022 Yoshimichi ANDOH
!Released under the MIT license
!https://opensource.org/licenses/mit-license.php

! === inputs ===
! (1) multiple .gr files, generated by molgr.F90
!
	implicit none
        real(8) :: rho, volume
        real(8) :: srho, svolume
        integer(4) :: ndr, rflame
        integer(4) :: srflame
        integer(4) :: i, nfile
	character(1) :: dum
        real(8) :: gr, sdv
	real(8),allocatable :: rr(:)
        real(8),allocatable :: sgr(:),sgr2(:)

	nfile=0
	srho=0d0
	svolume=0d0
	srflame=0
1	continue
	read(*,*,end=99) dum, rho, volume, ndr, rflame
        srho=srho+rho
        svolume=svolume+volume
        srflame=srflame+rflame
	if(.not.allocated(sgr))then
          allocate( rr(ndr), sgr(ndr), sgr2(ndr) )
          sgr=0d0
          sgr2=0d0
        endif
	do i=1,ndr
          read(*,*) rr(i), gr
          sgr(i)=sgr(i)+gr
          sgr2(i)=sgr2(i)+gr**2
	enddo
        nfile=nfile+1
        goto 1
99	continue

        sgr=sgr/dble(nfile)
        sgr2=sgr2/dble(nfile)
        srho=srho/dble(nfile)
        svolume=svolume/dble(nfile)

!### output ###
        write(*,'(a1,2e22.15,i5,i7)') '#', srho, svolume, ndr, srflame
        do i=1,ndr
          sdv=sqrt(sgr2(i)-sgr(i)**2)
	  write(*,'(f12.5,2e20.10)') rr(i),sgr(i),sdv
        enddo

	stop
	end
